###############################################################################
# JenkinsX configuration parameters
###############################################################################

# This section is used by JenkinsX to import application jobs from Bitbucket
# repository.
# IMPORTANT NOTE - This section is mandatory, however it will be used only with
# application deployed by JenkinsX.

# Below parameters can be taken from Bitbucket settings section:
# Repo username with assigned token to access repository
# Example:
# gitUsername: 'mygitusername'
# gitApiToken: '55b8bfdc5c74833fb125140a45a7e4786b11ba7f '

gitUsername: ''
gitApiToken: ''

# Provider Url is used to handle API Calls
# Example:
# gitProviderUrl: 'https://myorganization.com/bitbucket/'
gitProviderUrl: ''

# Bitbucket repository address
# Example:
# gitBitbucketServer: 'https://git.myorganization.com/'
gitBitbucketServer: ''

# Default password to access JenkinsX dashboard
# Example:
# defaultAdminPassword: 'qwerty'
defaultAdminPassword: 'qwerty'

# domainHostedZoneID is an AWS Route53 parameter to store Domain used e.g. for LMA
# Example:
# domainHostedZoneID: 'Z9NMCFPV6TPZZR'

domainHostedZoneID: ''

# domainAliasPrefix is a string for wildcard alias that will be created (e.g. for LMA ingress)
# Example:
# domainAliasPrefix: 'demoapp'

domainAliasPrefix: 'demoapp'

# jxDomainHostedZoneID is an AWS Route53 parameter to store Domain for Jx
# This is for backward compatibility with (experimental) jx support.
# Example:
# jxDomainHostedZoneID: 'Z9NMCFPV6TPZZR'

jxDomainHostedZoneID: ''

# jxDomainAliasPrefix is a string for wildcard alias that will be created (*.jxDomainAliasPrefix.DOMAIN)
# This is for backward compatibility with (experimental) jx support.
# Example:
# jxDomainAliasPrefix: 'demoapp'

jxDomainAliasPrefix: 'demoapp'
